name: Peace 3 CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "10.0.x"

      - name: Restore
        run: dotnet restore day-3/Peace3/QuotesApi.Tests/QuotesApi.Tests.csproj

      - name: Test
        run: dotnet test day-3/Peace3/QuotesApi.Tests/QuotesApi.Tests.csproj --no-restore --logger "console;verbosity=detailed"